name: fonoteke
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.14
  device_info_plus: ^11.1.1
  flutter_animate: ^4.5.0
  easy_localization: ^3.0.7
  go_router: ^14.6.0
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  logging: ^1.3.0
  logger: ^2.4.0
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  equatable: ^2.0.5
  formz: ^0.7.0
  just_audio_background: ^0.0.1-beta.13
  rxdart: ^0.28.0
  audio_service: ^0.18.15
  provider: ^6.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
